#!usr/bin/python
# Code to add two matrices using numpy
import numpy as np

def add(X,Y,Z):
    return np.add(X,Y,Z)

if __name__=='__main__':
    X=np.matrix([[1, 2, 3], [2, 3, 4]])
    Y=np.matrix([[2, 2, 2], [1, 4, 5]])
    Z=np.matrix([[3,4,5],[6,7,8]])
    R=add(X,Y,Z)
    print R
